apiVersion: v1
kind: Service
metadata:
  name: devops-mysql
  labels:
    app: devops
spec:
  ports:
  - port: 3306
  selector:
    app: devops
    tier: mysql
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-mysql-pv
  labels:
    app: devops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-mysql
  labels:
    app: devops
spec:
  selector:
    matchLabels:
      app: devops
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devops
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.11
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: DB_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: DB_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: devops-mysql-pv