apiVersion: v1
kind: Service
metadata:
  name: devops-web
  labels:
    app: devops-web
spec:
  ports:
  - port: 7000
  selector:
    app: devops-web
    tier: backend-api
  type: LoadBalancer
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pv
  labels:
    app: devops-web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web
  labels:
    app: devops-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-web
      tier: backend-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devops-web
        tier: backend-api
    spec:
      initContainers:
      - name: setup-storage
        image: busybox
        command: ["sh", "-c", "mkdir -p /var/www/html/storage/framework/views/ && mkdir -p /var/www/html/storage/framework/cache/ && mkdir -p /var/www/html/storage/framework/sessions/ && chown -R www-data:www-data /var/www/html/storage/framework/sessions/"]
        volumeMounts:
        - name: devops-web-persistent-storage
          mountPath: /var/www/html/storage
      containers:
      - image: collingitonga/e-commerce:dev
        name: devops-web
        envFrom:
        - secretRef:
            name: devops-secrets
        ports:
        - containerPort: 7000
          name: devops-web
        volumeMounts:
        - name: devops-web-persistent-storage
          mountPath: /var/www/html/storage
      volumes:
      - name: devops-web-persistent-storage
        persistentVolumeClaim:
          claimName: web-pv





