apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
      - name: e-commerce
        image: collingitonga/e-commerce:dev
        ports:
        - containerPort: 7000
        env:
        - name: DB_HOST
          value: e-commerce.*.us-east-1.rds.amazonaws.com
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: DB_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devops-secrets
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: e-commerce
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: ClusterIP 