name: Build and Deploy Laravel app
on:
    push:
        branches:
            - develop
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD}}
            
            - name: Build Docker image
              uses: docker/build-push-action@v3
              with: 
                context: . 
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/e-commerce:dev
        
    deploy:
        needs: build-and-push 
        runs-on: ubunutu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: copy files to target server via scp
              uses: appleboy/scp-action@v0.1.3
              with:
                host: ${{ secrets.DEPLOY_HOST }}
                username: ${{ secrets.DEPLOY_USERNAME }}
                port: 22
                key: ${{ secrets.DEPLOY_KEY }}
                strip_components: 2
                source: "./deployments/envs.yml,./deployments/kustomization.yaml,./deployments/nginx,yaml,./deployments/web.yaml"
                target: "~/.ecommerce/${{ github.event.repository.name }}/"

            - name: remote login via ssh
              uses: appleboy/ssh-action@v1.0.3
              env:
                APPTOKEN: ${{ secrets.ACCESS_TOKEN }}
                GITHUB_ACTOR: ${{ secrets.actor }}
              with:
                host: ${{ secrets.DEPLOY_HOST }}
                username: ${{ secrets.DEPLOY_USERNAME }}
                key: ${{ secrets.DEPLOY_KEY }}
                port: 22
                envs: APPTOKEN,GITHUB_ACTOR
                script: |
                  echo $APPTOKEN | docker login -u $GITHUB_ACTOR --password-stdin
                  cd ~/.ecommerce/${{ github.event.repository.name }}
                  kubectl apply -f kustomization.yaml