name: Build and Deploy Laravel app
on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD}}
            
            - name: Build Docker image
              uses: docker/build-push-action@v3
              with: 
                context: . 
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/e-commerce:latest
        
    deploy:
        runs-on: ubunutu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Kubernetes context
              uses: azure/k8s-set-context@v1
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}
      
            - name: Deploy to Kubernetes
              run: |
                kubectl apply -f deployment.yaml
                kubectl apply -f service.yaml